#page title
page_title                                : LabGear – Medical Lab Tests                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 350942163                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.smartddx.labgearessentials                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : LabGear                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A Clinician's Lab  Pocket book 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Raheel Sayeed, MD                              
your_link                                 : https://vimatics.com                     
your_city                                 : Hyd & Boston                                
email_address                             : support@smartddx.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : medicalgear
github_username                           : raheelsayeed
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Pocket Lab Tests Reference
    description                           : LabGear is the most advanced pocket tool for Medical Laboratory tests with peer reviewed content for all health care professionals - students, physicians, nurses
    fontawesome_icon_name                 : flask
    
  - title                                 : More than 300 Tests
    description                           : Covers all major blood tests from major organ systems including testing panels, tumor markers and toxicology
    fontawesome_icon_name                 : heart
 
  - title                                 : Differential Diagnosis & Symptoms
    description                           : Comprehensive library of medical lab tests with differential diagnosis and associated characteristic presenting signs and symptoms
    fontawesome_icon_name                 : stethoscope

  - title                                 : Chemistry Panels 
    description                           : Basic Metabolic Panel, Comprehensive Metabolic Panel, Complete blood Picture, Arterial Blood Gases, Liver Panel, Lipid Profile, Coagulation Profile, Diabetic Profile including fishbone schematics
    fontawesome_icon_name                 : vials


  - title                                 : Color Indicators 
    description                           : Containers for sample collections differ by the blood test type. LabGear has clear color indicators for each of the tests for fast reference
    fontawesome_icon_name                 : vial



  - title                                 : Covid 19 Checklist
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : virus


  - title                                 : Reference Links
    description                           : Articles contain reference links to PubMed, Medscape, LabTestsOnline and Wikipedia 
    fontawesome_icon_name                 : link

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       :  "#ffffff"
cover_overlay_transparency                :  0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#0000ff"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
